{
  "compatibilityLevel": 1606,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Customers\", \"Field Quality\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "customers.avg_rating": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Customers",
                    "ConceptualProperty": "Avg Rating"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Avg rating": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "customers.dissatisfied_": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Customers",
                    "ConceptualProperty": "Dissatisfied %"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Dissatisfied": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "customers.h1_revenue": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Customers",
                    "ConceptualProperty": "H1 Revenue"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Jan-Jun revenue": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "customers.order_share": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Customers",
                    "ConceptualProperty": "Order Share"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "% of orders": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "customers.product_category": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Customers",
                    "ConceptualProperty": "Product_Category"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Category": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "customers.revenue_share": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Customers",
                    "ConceptualProperty": "Revenue Share"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "% of revenue": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "customers.satisfied_": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Customers",
                    "ConceptualProperty": "Satisfied %"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Satisfied": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "866fda8f-43c0-4fab-8adf-4d9df1514aed",
        "fromColumn": "Purchase_Date",
        "fromTable": "Customers",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Customers",
        "columns": [
          {
            "name": "Customer_ID",
            "dataType": "string",
            "lineageTag": "e32a6b13-2598-46be-b4c9-b5872bb88cfc",
            "sourceColumn": "Customer_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "dataType": "string",
            "lineageTag": "2c8ccb77-e0ce-4895-b31d-6d757f0a26b8",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "First_Name",
            "dataType": "string",
            "lineageTag": "6babaf21-bf0e-4ee6-801d-de1497f305e4",
            "sourceColumn": "First_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Last_Name",
            "dataType": "string",
            "lineageTag": "b36e3c04-1c16-4322-ac59-b7c9f50baeb6",
            "sourceColumn": "Last_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "lineageTag": "75c46e71-e954-4de2-88dc-80be3f35d1cb",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Gender_Name_Conflict",
            "dataType": "string",
            "lineageTag": "26a87777-bfc0-4e88-8aee-05ecb81a95b9",
            "sourceColumn": "Gender_Name_Conflict",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "33e69f10-2b15-4b5a-a37e-57f753868ba6",
            "sourceColumn": "Age",
            "summarizeBy": "none"
          },
          {
            "name": "Age_Group",
            "dataType": "string",
            "lineageTag": "164fb0f6-3281-45c7-8c5d-05c10212b631",
            "sortByColumn": "AgeSort",
            "sourceColumn": "Age_Group",
            "summarizeBy": "none"
          },
          {
            "name": "Age_Status",
            "dataType": "string",
            "lineageTag": "2ca5da36-6bd7-43ca-a99a-966e433cfad8",
            "sourceColumn": "Age_Status",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "dataType": "string",
            "lineageTag": "8a0d5edf-297f-4ed5-bfa2-74989a167b3c",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "Email_Domain",
            "dataType": "string",
            "lineageTag": "a0d710e8-2581-489a-9eec-b80d9dafa76b",
            "sourceColumn": "Email_Domain",
            "summarizeBy": "none"
          },
          {
            "name": "Phone_Status",
            "dataType": "string",
            "lineageTag": "6678afa2-829c-4c39-8f0b-ae12a5b98632",
            "sourceColumn": "Phone_Status",
            "summarizeBy": "none"
          },
          {
            "name": "Purchase_Amount",
            "dataType": "double",
            "formatString": "\\$#,0.00",
            "lineageTag": "327a35ac-c21d-4529-acaf-d936bda9020b",
            "sourceColumn": "Purchase_Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount_Status",
            "dataType": "string",
            "lineageTag": "44f07112-8a66-415e-8c29-69f8b12608f9",
            "sourceColumn": "Amount_Status",
            "summarizeBy": "none"
          },
          {
            "name": "Spend_Band",
            "dataType": "string",
            "lineageTag": "f36494a3-d3e2-4bf7-be10-b2bdd22fa3cd",
            "sortByColumn": "BandSort",
            "sourceColumn": "Spend_Band",
            "summarizeBy": "none"
          },
          {
            "name": "Purchase_Date",
            "annotations": [
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "8ab8c9df-9b96-431c-a19d-b552f28c396d",
            "sourceColumn": "Purchase_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date_Status",
            "dataType": "string",
            "lineageTag": "5e3a758e-1d8f-42ee-91f3-ebab949b5cea",
            "sourceColumn": "Date_Status",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f1f52a3-5787-4b33-a22a-18c5b70027dd",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "lineageTag": "edefac9f-766d-4b3e-b7b1-01e742169ba1",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year_Month",
            "dataType": "string",
            "lineageTag": "04026264-d684-43fb-8032-6d440d0dd649",
            "sourceColumn": "Year_Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month_Num",
            "dataType": "int64",
            "lineageTag": "5e52e81f-fffd-402a-9a92-9828ed64b4e3",
            "sourceColumn": "Month_Num",
            "summarizeBy": "none"
          },
          {
            "name": "Month_Name",
            "dataType": "string",
            "lineageTag": "a350716c-d7cd-4001-9ff5-8d0104155451",
            "sortByColumn": "Month_Num",
            "sourceColumn": "Month_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday_Num",
            "dataType": "int64",
            "lineageTag": "e2350cda-e11e-4e9b-b42d-bbda961be868",
            "sourceColumn": "Weekday_Num",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday",
            "dataType": "string",
            "lineageTag": "e87b034b-dab3-4342-82da-613bef6900e7",
            "sortByColumn": "Weekday_Num",
            "sourceColumn": "Weekday",
            "summarizeBy": "none"
          },
          {
            "name": "Full_Month",
            "dataType": "string",
            "lineageTag": "cfbf2e8f-0305-4be3-99fe-dfbe38579552",
            "sourceColumn": "Full_Month",
            "summarizeBy": "none"
          },
          {
            "name": "Product_Category",
            "dataType": "string",
            "lineageTag": "78a59570-d0b0-4bac-89e3-a32e5aa55569",
            "sourceColumn": "Product_Category",
            "summarizeBy": "none"
          },
          {
            "name": "Rating",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c089666e-4c60-480e-a299-ceeab679cd42",
            "sourceColumn": "Rating",
            "summarizeBy": "none"
          },
          {
            "name": "Rating_Status",
            "dataType": "string",
            "lineageTag": "cc08f88f-cf60-4706-9e2e-8350be6f417e",
            "sourceColumn": "Rating_Status",
            "summarizeBy": "none"
          },
          {
            "name": "Rating_Band",
            "dataType": "string",
            "lineageTag": "2e331271-0607-4a0c-a098-89ea07d5b360",
            "sortByColumn": "RatingBandSort",
            "sourceColumn": "Rating_Band",
            "summarizeBy": "none"
          },
          {
            "name": "Valid_Fields",
            "dataType": "int64",
            "lineageTag": "0dd40bc2-928a-411e-9e02-082d99ac8ed6",
            "sourceColumn": "Valid_Fields",
            "summarizeBy": "none"
          },
          {
            "name": "Complete_Record",
            "dataType": "string",
            "lineageTag": "5e21c7e4-9aba-4977-9aa7-9856ccf285d1",
            "sourceColumn": "Complete_Record",
            "summarizeBy": "none"
          },
          {
            "name": "AgeSort",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ca12e032-5e52-49c2-9aea-b2ca4429daaa",
            "sourceColumn": "AgeSort",
            "summarizeBy": "none"
          },
          {
            "name": "BandSort",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "819f95c8-c718-42a0-994a-5b6567911b40",
            "sourceColumn": "BandSort",
            "summarizeBy": "none"
          },
          {
            "name": "RatingBandSort",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "03c28524-ec18-40f3-8581-22410eb76328",
            "sourceColumn": "RatingBandSort",
            "summarizeBy": "none"
          },
          {
            "name": "Stars",
            "dataType": "string",
            "lineageTag": "33e074a4-54ea-437f-b3c2-faa4f3d4c51b",
            "sourceColumn": "Stars",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "552a4ff4-02cb-47e6-b0d0-5694466e4ed0",
        "measures": [
          {
            "name": "Customers",
            "description": "Customers: unique customer IDs (one purchase each)",
            "expression": "COUNTROWS ( Customers )",
            "formatString": "#,0",
            "lineageTag": "b828ec17-2cce-4f11-b8ea-549bbaccd5ca"
          },
          {
            "name": "Revenue",
            "description": "Revenue: recorded amounts only (97 blanks are not estimated)",
            "expression": "SUM ( Customers[Purchase_Amount] )",
            "formatString": "\\$#,0",
            "lineageTag": "ee39eecc-9db0-4160-9f3f-0cbb814474eb"
          },
          {
            "name": "Priced Orders",
            "description": "Revenue: purchases with a recorded amount",
            "expression": "COUNT ( Customers[Purchase_Amount] )",
            "formatString": "#,0",
            "lineageTag": "a0b2cc16-d11e-4a89-8254-edd7c430d9aa"
          },
          {
            "name": "AOV",
            "description": "Revenue: average order value",
            "expression": "AVERAGE ( Customers[Purchase_Amount] )",
            "formatString": "\\$#,0",
            "lineageTag": "ef1ec01d-a6fe-44bc-b7d9-70b61587fd58"
          },
          {
            "name": "Median Order",
            "description": "Revenue: median order value",
            "expression": "MEDIAN ( Customers[Purchase_Amount] )",
            "formatString": "\\$#,0",
            "lineageTag": "6b7515a7-94d4-4712-844c-667c9e478fe1"
          },
          {
            "name": "Valid Ratings",
            "description": "Satisfaction: ratings on the 1-5 scale (blank and '10' excluded)",
            "expression": "COUNT ( Customers[Rating] )",
            "formatString": "#,0",
            "lineageTag": "2d9e03ca-127e-450a-b362-ce018815735f"
          },
          {
            "name": "Rated",
            "description": "Valid ratings, blank when zero (hides 'No rating' in stacked charts)",
            "expression": "VAR r = [Valid Ratings] RETURN IF ( r > 0, r )",
            "formatString": "#,0",
            "lineageTag": "df49d190-46da-4cb5-9b04-a61eb4a2925b"
          },
          {
            "name": "Avg Rating",
            "description": "Satisfaction: average of valid ratings",
            "expression": "AVERAGE ( Customers[Rating] )",
            "formatString": "0.00",
            "lineageTag": "9c794bf2-b7c3-432b-b975-ae42615f2cc9"
          },
          {
            "name": "Satisfied %",
            "description": "Satisfaction: 4-5 star share",
            "expression": "DIVIDE ( CALCULATE ( [Valid Ratings], Customers[Rating] >= 4 ), [Valid Ratings] )",
            "formatString": "0.0%",
            "lineageTag": "ee1b74d1-de19-49c8-9eff-a2f0b5046cff"
          },
          {
            "name": "Dissatisfied %",
            "description": "Satisfaction: 1-2 star share",
            "expression": "DIVIDE ( CALCULATE ( [Valid Ratings], Customers[Rating] <= 2 ), [Valid Ratings] )",
            "formatString": "0.0%",
            "lineageTag": "f1ace1e4-d917-4275-98de-97d0776044ae"
          },
          {
            "name": "Net Satisfaction",
            "description": "Satisfaction: satisfied minus dissatisfied",
            "expression": "[Satisfied %] - [Dissatisfied %]",
            "formatString": "+0.0%;-0.0%;0.0%",
            "lineageTag": "df1d4f11-8b33-4b14-8b86-0f7142798a4c"
          },
          {
            "name": "Rating Share",
            "description": "Share of valid ratings at each star level",
            "expression": "VAR r = [Valid Ratings] RETURN IF ( r > 0, DIVIDE ( r, CALCULATE ( [Valid Ratings], ALLSELECTED ( Customers[Stars] ) ) ) )",
            "formatString": "0.0%",
            "lineageTag": "cb62ad8a-7291-4945-89b3-3b20a8e3eb6e"
          },
          {
            "name": "Complete Records %",
            "description": "Data quality: age, gender, amount, date, category and rating all valid",
            "expression": "DIVIDE ( CALCULATE ( [Customers], Customers[Complete_Record] = \"Yes\" ), [Customers] )",
            "formatString": "0.0%",
            "lineageTag": "0e941be1-5158-4732-8587-ccded90c34a2"
          },
          {
            "name": "Usable Age %",
            "description": "Data quality: real ages (not -1 / 200 / blank)",
            "expression": "DIVIDE ( CALCULATE ( [Customers], Customers[Age_Status] = \"Valid\" ), [Customers] )",
            "formatString": "0.0%",
            "lineageTag": "46a29f25-ece3-4b72-97cc-8be314fd8edf"
          },
          {
            "name": "Customers with Age",
            "description": "Customers with a real age",
            "expression": "CALCULATE ( [Customers], Customers[Age_Status] = \"Valid\" )",
            "formatString": "#,0",
            "lineageTag": "30d1e0b7-fd57-4a76-9362-4dacf9169af4"
          },
          {
            "name": "Customer Share",
            "description": "Share of the current selection",
            "expression": "DIVIDE ( [Customers], CALCULATE ( [Customers], ALLSELECTED ( Customers ) ) )",
            "formatString": "0.0%",
            "lineageTag": "289173ea-5719-4453-b3c3-5f65e695f577"
          },
          {
            "name": "Order Share",
            "description": "Share of priced orders in the selection",
            "expression": "DIVIDE ( [Priced Orders], CALCULATE ( [Priced Orders], ALLSELECTED ( Customers ) ) )",
            "formatString": "0%",
            "lineageTag": "74015ab1-c259-4754-8382-066ceab1a369"
          },
          {
            "name": "Revenue Share",
            "description": "Share of revenue in the selection",
            "expression": "DIVIDE ( [Revenue], CALCULATE ( [Revenue], ALLSELECTED ( Customers ) ) )",
            "formatString": "0%",
            "lineageTag": "a0869061-3993-43f1-a33b-c3a68c58c1a8"
          },
          {
            "name": "Big Ticket Revenue %",
            "description": "Revenue from $750+ orders",
            "expression": "DIVIDE ( CALCULATE ( [Revenue], Customers[Spend_Band] = \"$750+\" ), [Revenue] )",
            "formatString": "0%",
            "lineageTag": "7505f1bb-9b7c-4503-b874-5de5bb73c691"
          },
          {
            "name": "Unassigned Revenue %",
            "description": "Revenue with no product category",
            "expression": "DIVIDE ( CALCULATE ( [Revenue], Customers[Product_Category] = \"Unknown\" ), [Revenue] )",
            "formatString": "0%",
            "lineageTag": "626b5dfc-1b02-4193-8b04-f71d3f9efcc3"
          },
          {
            "name": "Full Months",
            "description": "Trend: complete months in the selected period (Oct 2022 and Jul 2025 are partial)",
            "expression": "CALCULATE ( DISTINCTCOUNT ( 'Calendar'[Year_Month] ), KEEPFILTERS ( 'Calendar'[Year_Month] >= \"2022-11\" && 'Calendar'[Year_Month] <= \"2025-06\" ) )",
            "formatString": "0",
            "lineageTag": "05619d57-1b47-41f0-a78c-5c43791d302e"
          },
          {
            "name": "Purchases per Month",
            "description": "Trend: purchases per full month",
            "expression": "DIVIDE ( CALCULATE ( [Customers], Customers[Full_Month] = \"Yes\" ), [Full Months] )",
            "formatString": "0.0",
            "lineageTag": "42fad95f-ba07-4df2-bbec-df6be44a1f87"
          },
          {
            "name": "Revenue per Month",
            "description": "Trend: revenue per full month",
            "expression": "DIVIDE ( CALCULATE ( [Revenue], Customers[Full_Month] = \"Yes\" ), [Full Months] )",
            "formatString": "\\$#,0",
            "lineageTag": "fccf20fe-1b73-4bb2-86f4-8a32cb1f9644"
          },
          {
            "name": "Full-Month Revenue",
            "description": "Trend: revenue, blank for the two partial months",
            "expression": "CALCULATE ( [Revenue], Customers[Full_Month] = \"Yes\" )",
            "formatString": "\\$#,0",
            "lineageTag": "488d7181-08bd-4040-a94b-8eeefeb82662"
          },
          {
            "name": "Full-Month Purchases",
            "description": "Trend: purchases, blank for the two partial months",
            "expression": "CALCULATE ( [Customers], Customers[Full_Month] = \"Yes\" )",
            "formatString": "#,0",
            "lineageTag": "4d07737d-0036-4458-8c81-8ba262866f03"
          },
          {
            "name": "Dated Purchases",
            "description": "Purchases with a valid date",
            "expression": "CALCULATE ( [Customers], Customers[Date_Status] = \"Valid\" )",
            "formatString": "#,0",
            "lineageTag": "b3462f70-fe87-4c94-8d2f-a7c73397d025"
          },
          {
            "name": "Days of Data",
            "description": "Calendar days covered by the data in the current filter",
            "expression": "COUNTROWS ( 'Calendar' )",
            "formatString": "#,0",
            "lineageTag": "addd1dc7-f047-4307-b56c-b2dcc3871022"
          },
          {
            "name": "Purchases per 30 Days",
            "description": "Seasonality: purchases per 30 days of data (fair across months that occur in 2 or 3 years)",
            "expression": "DIVIDE ( [Customers], [Days of Data] ) * 30",
            "formatString": "0.0",
            "lineageTag": "8a535faf-d8e1-4703-9d85-0c2baa4e942e"
          },
          {
            "name": "H1 Revenue",
            "description": "Trend: January-June revenue (like-for-like across years)",
            "expression": "CALCULATE ( [Revenue], KEEPFILTERS ( 'Calendar'[Month_Num] IN { 1, 2, 3, 4, 5, 6 } ) )",
            "formatString": "\\$#,0",
            "lineageTag": "808395d8-05ab-4143-ac87-f4de17660b20"
          },
          {
            "name": "Quality Rows",
            "description": "Data quality: customers per field and status (Usable / Blank / Invalid)",
            "expression": [
              "VAR k = SELECTEDVALUE ( 'Field Quality'[Field] ) & \"|\" & SELECTEDVALUE ( 'Field Quality'[Status] )",
              "RETURN",
              "    SWITCH ( k,",
              "        \"Purchase amount|Usable\", CALCULATE ( [Customers], Customers[Amount_Status] = \"Recorded\" ),",
              "        \"Purchase amount|Blank\", CALCULATE ( [Customers], Customers[Amount_Status] = \"Missing\" ),",
              "        \"Purchase date|Usable\", CALCULATE ( [Customers], Customers[Date_Status] = \"Valid\" ),",
              "        \"Purchase date|Invalid\", CALCULATE ( [Customers], Customers[Date_Status] = \"Invalid\" ),",
              "        \"Gender|Usable\", CALCULATE ( [Customers], Customers[Gender] <> \"Unknown\" ),",
              "        \"Gender|Blank\", CALCULATE ( [Customers], Customers[Gender] = \"Unknown\" ),",
              "        \"Product category|Usable\", CALCULATE ( [Customers], Customers[Product_Category] <> \"Unknown\" ),",
              "        \"Product category|Blank\", CALCULATE ( [Customers], Customers[Product_Category] = \"Unknown\" ),",
              "        \"Rating|Usable\", CALCULATE ( [Customers], Customers[Rating_Status] = \"Valid\" ),",
              "        \"Rating|Blank\", CALCULATE ( [Customers], Customers[Rating_Status] = \"Missing\" ),",
              "        \"Rating|Invalid\", CALCULATE ( [Customers], Customers[Rating_Status] = \"Out of range (10)\" ),",
              "        \"Age|Usable\", CALCULATE ( [Customers], Customers[Age_Status] = \"Valid\" ),",
              "        \"Age|Blank\", CALCULATE ( [Customers], Customers[Age_Status] = \"Missing\" ),",
              "        \"Age|Invalid\", CALCULATE ( [Customers], Customers[Age_Status] IN { \"Placeholder -1\", \"Placeholder 200\" } ),",
              "        \"Phone|Blank\", CALCULATE ( [Customers], Customers[Phone_Status] = \"Missing\" ),",
              "        \"Phone|Invalid\", CALCULATE ( [Customers], Customers[Phone_Status] = \"Placeholder\" )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "7f305d15-020a-495d-bf52-5b49e94b1942"
          }
        ],
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\nahla\\Desktop\\VOLTIX\\Task 9\\Cleaned_Customers.csv\"), [Delimiter = \",\", Columns = 31, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                "    Blanks = Table.ReplaceValue(Promoted, \"\", null, Replacer.ReplaceValue, {\"Age\", \"Purchase_Amount\", \"Purchase_Date\", \"Year\", \"Quarter\", \"Year_Month\", \"Month_Num\", \"Month_Name\", \"Weekday_Num\", \"Weekday\", \"Full_Month\", \"Rating\"}),",
                "    Typed = Table.TransformColumnTypes(Blanks, {{\"Customer_ID\", type text}, {\"Name\", type text}, {\"First_Name\", type text}, {\"Last_Name\", type text}, {\"Gender\", type text}, {\"Gender_Name_Conflict\", type text}, {\"Age\", Int64.Type}, {\"Age_Group\", type text}, {\"Age_Status\", type text}, {\"Email\", type text}, {\"Email_Domain\", type text}, {\"Phone_Status\", type text}, {\"Purchase_Amount\", type number}, {\"Amount_Status\", type text}, {\"Spend_Band\", type text}, {\"Purchase_Date\", type date}, {\"Date_Status\", type text}, {\"Year\", Int64.Type}, {\"Quarter\", type text}, {\"Year_Month\", type text}, {\"Month_Num\", Int64.Type}, {\"Month_Name\", type text}, {\"Weekday_Num\", Int64.Type}, {\"Weekday\", type text}, {\"Full_Month\", type text}, {\"Product_Category\", type text}, {\"Rating\", Int64.Type}, {\"Rating_Status\", type text}, {\"Rating_Band\", type text}, {\"Valid_Fields\", Int64.Type}, {\"Complete_Record\", type text}}, \"en-US\"),",
                "    AgeSort = Table.AddColumn(Typed, \"AgeSort\", each List.PositionOf({\"15-29\", \"30-44\", \"45-59\", \"60-74\", \"75-90\", \"Unknown\"}, [Age_Group]) + 1, Int64.Type),",
                "    BandSort = Table.AddColumn(AgeSort, \"BandSort\", each List.PositionOf({\"Under $250\", \"$250-499\", \"$500-749\", \"$750+\", \"Unknown\"}, [Spend_Band]) + 1, Int64.Type),",
                "    RatingSort = Table.AddColumn(BandSort, \"RatingBandSort\", each List.PositionOf({\"Dissatisfied (1-2)\", \"Neutral (3)\", \"Satisfied (4-5)\", \"No rating\"}, [Rating_Band]) + 1, Int64.Type),",
                "    Stars = Table.AddColumn(RatingSort, \"Stars\", each if [Rating] = null then null else Text.From([Rating]) & \" star\", type text)",
                "in",
                "    Stars"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "70484a83-c94e-44ff-8aa3-ada02051f53c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3e16e64c-12ab-41c5-bc5f-1040a7f13fb6",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month_Num",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8f87aaef-daa3-428b-b565-21c27fcd9018",
            "sourceColumn": "[Month_Num]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c15459c3-4503-4e1d-a0f5-56966783a7a2",
            "sortByColumn": "Month_Num",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year_Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "47413981-7cba-48ed-bed4-45514fce43e2",
            "sourceColumn": "[Year_Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "38979679-6f72-4ef9-939f-6c106804bb10",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": "ADDCOLUMNS ( CALENDAR ( DATE ( 2022, 10, 27 ), DATE ( 2025, 7, 23 ) ), \"Year\", YEAR ( [Date] ), \"Month_Num\", MONTH ( [Date] ), \"Month\", FORMAT ( [Date], \"MMM\" ), \"Year_Month\", FORMAT ( [Date], \"YYYY-MM\" ) )",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Field Quality",
        "columns": [
          {
            "name": "Field",
            "dataType": "string",
            "lineageTag": "5383b64c-a5ba-496c-99fc-7cd71f110068",
            "sortByColumn": "FieldSort",
            "sourceColumn": "Field",
            "summarizeBy": "none"
          },
          {
            "name": "FieldSort",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9abbac50-c883-45c5-8c5e-0a5daf404e11",
            "sourceColumn": "FieldSort",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "dataType": "string",
            "lineageTag": "9b751d1c-fa4c-477f-bb90-d723b7b487b0",
            "sortByColumn": "StatusSort",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "StatusSort",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "40f0c917-9f7a-4afd-be21-d80db9d9d724",
            "sourceColumn": "StatusSort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c99212ea-4fe3-443e-8baf-d6d1d6cd7eef",
        "partitions": [
          {
            "name": "Field Quality",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #table(type table [Field = text, FieldSort = Int64.Type, Status = text, StatusSort = Int64.Type], {{\"Purchase amount\", 1, \"Usable\", 1}, {\"Purchase amount\", 1, \"Blank\", 2}, {\"Purchase amount\", 1, \"Invalid\", 3}, {\"Purchase date\", 2, \"Usable\", 1}, {\"Purchase date\", 2, \"Blank\", 2}, {\"Purchase date\", 2, \"Invalid\", 3}, {\"Gender\", 3, \"Usable\", 1}, {\"Gender\", 3, \"Blank\", 2}, {\"Gender\", 3, \"Invalid\", 3}, {\"Product category\", 4, \"Usable\", 1}, {\"Product category\", 4, \"Blank\", 2}, {\"Product category\", 4, \"Invalid\", 3}, {\"Rating\", 5, \"Usable\", 1}, {\"Rating\", 5, \"Blank\", 2}, {\"Rating\", 5, \"Invalid\", 3}, {\"Age\", 6, \"Usable\", 1}, {\"Age\", 6, \"Blank\", 2}, {\"Age\", 6, \"Invalid\", 3}, {\"Phone\", 7, \"Usable\", 1}, {\"Phone\", 7, \"Blank\", 2}, {\"Phone\", 7, \"Invalid\", 3}})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}